# Generated by Django 4.2.7 on 2024-11-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("date_of_birth", models.DateField()),
                ("date_of_registration", models.DateField()),
                ("address_street_number", models.IntegerField()),
                ("address_street_name", models.TextField()),
                ("address_apt_number", models.CharField(max_length=6)),
                ("address_zip_code", models.IntegerField()),
                ("party_affiliation", models.CharField(max_length=1)),
                ("precinct_number", models.IntegerField()),
                ("v20state", models.BooleanField()),
                ("v21town", models.BooleanField()),
                ("v21primary", models.BooleanField()),
                ("v22general", models.BooleanField()),
                ("v23town", models.BooleanField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
