# Generated by Django 4.2.7 on 2024-11-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voter_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="address_apt_number",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="voter",
            name="precinct_number",
            field=models.CharField(max_length=2),
        ),
    ]
