# Generated by Django 4.2.7 on 2024-11-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="author_website",
        ),
        migrations.AddField(
            model_name="author",
            name="author_birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="author",
            name="author_death_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
