# Generated by Django 4.2.7 on 2024-11-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_remove_author_author_website_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookprogress",
            name="rating",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
            ),
        ),
    ]
