# Generated by Django 4.2.7 on 2024-12-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_friendrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendrequest",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending")], default="pending", max_length=20
            ),
        ),
    ]
