# Generated by Django 4.2.7 on 2024-12-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_alter_friendrequest_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookprogress",
            name="rating",
        ),
    ]
