# Generated by Django 4.2.7 on 2024-10-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0006_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.URLField(blank=True),
        ),
    ]
