# Generated by Django 4.2.7 on 2024-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0009_alter_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusmessage",
            name="image_file",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.URLField(blank=True),
        ),
    ]
